INFO     [🔧TEST CONFIG]:conftest.py:87 Loading test configuration
INFO     [🔧TEST CONFIG]:conftest.py:388 Navigating to: https://console.dev.apolo.us/
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body:
<not available>
Response Body (first 1000 chars):
{"authorized": false, "auth_url": "https://auth.dev.apolo.us/authorize", "token_url": "https://auth.dev.apolo.us/oauth/token", "logout_url": "https://auth.dev.apolo.us/v2/logout?returnTo=https://console.dev.apolo.us", "client_id": "q3I0OzzGnTDkhRmpeJ7WWgaTCucmVxTL", "audience": "https://api.dev.apolo.us", "callback_urls": ["http://127.0.0.1:54540", "http://127.0.0.1:54541", "http://127.0.0.1:54542"], "headless_callback_url": "https://api.dev.apolo.us/oauth/show-code", "success_redirect_url": "https://api.dev.apolo.us/oauth/login"}
INFO     [🔧TEST CONFIG]:conftest.py:93 Creating data manager
INFO     [🔧TEST CONFIG]:conftest.py:123 Creating users manager
INFO     [🔧TEST CONFIG]:conftest.py:109 Creating API helper
INFO     [🔧TEST CONFIG]:conftest.py:117 Creating Apolo CLI instance
INFO     [👤UsersManager]:users_manager.py:73 Setting main user to UserData(email='regression-djhqu92oz6@apolo.us', username='regression-djhqu92oz6', password='@R4558y*1qlE')
INFO     [👤UsersManager]:users_manager.py:82 Setting second user to None
INFO     [👤UsersManager]:users_manager.py:91 Setting third user to None
INFO     [📘TEST_INFO]:reporting.py:86 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:87 📝 TEST started: Import Shell app config via UI
INFO     [📘TEST_INFO]:reporting.py:88 ------------------------------------------------------------
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Login via UI
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click login button
INFO     [🎭 Playwright]:base_page.py:16 <AuthPage>: Click log in button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click login button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_login_button_success_18291a.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter email
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter regression-djhqu92oz6@apolo.us email
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter email
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_email_success_bf9293.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Enter password
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Enter ********* password
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Enter password
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_enter_password_success_536857.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Continue button
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Click continue button
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/api/v1/config
Request Body:
<not available>
Response Body (first 1000 chars):
{"authorized": true, "orgs": [{"name": "regression-org-j4snf5w5xexk", "role": "admin"}], "clusters": [{"name": "default", "registry_url": "https://registry.api.dev.apolo.us", "storage_url": "https://api.dev.apolo.us/api/v1/storage", "monitoring_url": "https://monitoring.api.dev.apolo.us/api/v1/jobs", "secrets_url": "https://api.dev.apolo.us/api/v1/secrets", "metrics_url": "https://grafana.dev.apolo.us", "disks_url": "https://api.dev.apolo.us/api/v1/disk", "buckets_url": "https://api.dev.apolo.us/api/v1/buckets", "resource_pool_types": [{"name": "a2-highgpu-1g", "min_size": 0, "max_size": 10, "cpu": 12.0, "available_cpu": 11.101, "memory": 89629032448, "available_memory": 80898240256, "disk_size": 523982073856, "available_disk_size": 364209683290, "nvidia_gpu": {"count": 1, "model": "NVIDIA-A100-SXM4-40GB", "memory": 42949672960}}, {"name": "a2-highgpu-2g", "min_size": 0, "max_size": 3, "cpu": 24.0, "available_cpu": 23.73, "memory": 179367243776, "available_memory": 168094003200, "disk_
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/api/v1/users/regression-djhqu92oz6/permissions?uri=blob:
Request Body:
<not available>
Response Body (first 1000 chars):
[{"uri": "blob://default/regression-org-j4snf5w5xexk", "action": "manage"}]
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/orgs/regression-org-j4snf5w5xexk
Request Body:
<not available>
Response Body (first 1000 chars):
{"name": "regression-org-j4snf5w5xexk", "balance": {"credits": "500", "spent_credits": "0"}, "user_default_credits": null, "notification_intervals": {"balance_projection_seconds": [604800, 259200, 86400], "balance_amount": [0], "balance_depletion_seconds": [86400, 604800]}}
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Waiting for spinner
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title
INFO     [🎭 Playwright]:base_page.py:16 <LoginPage>: Waiting for spinner to disappear
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/invites/incoming
Request Body:
<not available>
Response Body (first 1000 chars):
[]
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-djhqu92oz6?include=orgs
Request Body:
<not available>
Response Body (first 1000 chars):
{"name": "regression-djhqu92oz6", "email": "regression-djhqu92oz6@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-10-08T01:32:05.255275+00:00", "terms_accepted": true, "orgs": [{"org_name": "regression-org-j4snf5w5xexk", "role": "admin", "balance": {"spent_credits": "0"}}]}
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/admin/v1/users/regression-djhqu92oz6?include=clusters&include=system_role
Request Body:
<not available>
Response Body (first 1000 chars):
{"name": "regression-djhqu92oz6", "email": "regression-djhqu92oz6@apolo.us", "first_name": null, "last_name": null, "created_at": "2025-10-08T01:32:05.255275+00:00", "terms_accepted": true, "clusters": [{"cluster_name": "default", "role": "admin", "org_name": "regression-org-j4snf5w5xexk", "balance": {"spent_credits": "0"}}]}
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates/tags
Request Body:
<not available>
Response Body (first 1000 chars):
["AI","Agent","Apache","Apolo","Apolo Files","BI","Big data","Bundle","Business Intelligence","CLI","Chat","Container","Container registry","Data","Data processing","DeepSeek","Development","Diffusion","Dify","DockerHub","Document Processing","EDA","ELT","ETL","Easy Deploy","Embeddings","GPT","GptOSS","Graph","Hugging Face","IDE","Image generation","Inference","Jupyter","Knowledge Graph","LLM","LLMops","LLaMA","LightRAG","MLOps","Meta","Mistral","NLP","Notebooks","OpenAI","PostgreSQL","Postgres","RAG","RDBMS","Shell","Spark","Stable Diffusion","Storage","Superset","Text","VSCode","Vector Search","Vector search","Vector store","Visualization","Weaviate","experiment tracking","mlflow","model registry","vLLM"]
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates?page=1&size=50
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Continue button
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/templates?page=1&size=50
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[{"name":"aws-s3","title":"AWS S3","pub_date":"2025-01-01T00:00:00Z","description":"AWS S3 Storage","short_description":"","schema_version":1,"version":"HEAD","input":{"$defs":{"ApoloSecret":{"properties":{"key":{"title":"Key","type":"string"}},"required":["key"],"title":"ApoloSecret","type":"object","x-description":"Apolo Secret Configuration.","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Secret","x-type":"ApoloSecret"},"S3Params":{"properties":{"port":{"title":"Port","type":"integer"},"host":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Host"},"bucket":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Bucket"},"access_key":{"anyOf":[{"type":"string"},{"type":"null"}],"default":null,"title":"Access Key"},"secret_key":{"anyOf":[{"$ref":"#/$defs/ApoloSecret"},{"type":"null"}],"default":null}},"required":["port"],"title":"S3Params","type":"object"}},"properties":{"s3":{"$ref":"#/$defs/S3Params"}},"required":["s3"],"title
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_continue_button_success_a212f9.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Apps page displayed
INFO     [🎭 Playwright]:base_page.py:16 <AppsPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Apps page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_45f937.png
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Login via UI
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_login_success_5d867c.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Shell app container displayed on the main page
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Verify app container Shell displayed
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to Shell container...
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to Shell container...
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to Shell container...
INFO     [🎭 Playwright]:base_page.py:16 <MainPage>: Scroll to Shell container...
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Shell app container displayed on the main page
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_shell_container_displayed_success_e70bf8.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Install button on the Shell container
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v1/cluster/default/org/regression-org-j4snf5w5xexk/project/regression-proj-iyep8dqjfj/templates/shell
Request Body:
<not available>
Response Body (first 1000 chars):
[{"name":"shell","title":"Shell","pub_date":"2025-05-05T00:00:00Z","description":"Shell offers a powerful in-browser command-line interface with direct access to the Apolo platform. Preloaded with essential CLI tools, it enables you to manage resources, run scripts, and debug applications — all from a web-based terminal.","short_description":"A web-based remote shell instrumented with Apolo CLI, providing immediate access to dedicated compute resources","schema_version":1,"version":"v25.8.0","input":{"$defs":{"Networking":{"properties":{"http_auth":{"default":true,"description":"Whether to use HTTP authentication.","title":"HTTP Authentication","type":"boolean"}},"title":"Networking","type":"object","x-description":"Network settings","x-is-advanced-field":false,"x-meta-type":"inline","x-title":"Networking Settings","x-type":"Networking"},"Preset":{"properties":{"name":{"title":"Name","type":"string","x-description":"The name of the preset.","x-is-advanced-field":false,"x-meta-type":"in
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Install button on the Shell container
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_shell_container_click_install_btn_success_757fcd.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Shell install page displayed
INFO     [🎭 Playwright]:base_page.py:16 <ShellInstallPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Shell install page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_e282e8.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Import config button
INFO     [🎭 Playwright]:base_page.py:16 <ShellInstallPage>: Click Import config button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Import config button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_import_config_btn_success_536a28.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Import app config popup displayed
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Check if popup loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Import app config popup displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_popup_displayed_success_0fdbb8.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Get Shell app import config file path
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Get Shell app import config file path
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Import yaml config
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Import yaml config
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_import_yaml_config_success_fb6edc.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Click Apply config button
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Click Apply config button
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Click Apply config button
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_click_apply_config_btn_success_fdaf41.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Wait for Import app config popup disappear
INFO     [🎭 Playwright]:base_page.py:16 <ImportAppConfigPopup>: Wait for Import App Configuration popup to disappear
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Wait for Import app config popup disappear
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/ui_wait_to_disappear_success_1baf09.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify that Shell install page displayed
INFO     [🎭 Playwright]:base_page.py:16 <ShellInstallPage>: Check if page loaded
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify that Shell install page displayed
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_page_displayed_success_582a93.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Resource preset button value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Resource preset button value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_resource_preset_btn_value_success_23adb5.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify state of Http Auth checkbox
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify state of Http Auth checkbox
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_http_auth_checkbox_state_success_5dc2a4.png
INFO     [📘TEST_INFO]:reporting.py:37 ▶️ STEP started: Verify Display name value
INFO     [📘TEST_INFO]:reporting.py:51 ✅ STEP completed: Verify Display name value
INFO     [📘TEST_INFO]:reporting.py:225 📸 Screenshot captured and attached (success): /home/runner/work/apolo-test-automation/apolo-test-automation/reports/screenshots/verify_ui_display_name_value_success_b6947b.png
INFO     [📘TEST_INFO]:reporting.py:92 ✅ TEST completed: Import Shell app config via UI
INFO     [📘TEST_INFO]:reporting.py:98 ------------------------------------------------------------
INFO     [🌐API_helper]:api_helper.py:54 GET https://api.dev.apolo.us/apis/admin/v1/orgs
INFO     [🌐API_helper]:api_helper.py:175 Status: 200. Response: [{'name': 'regression-org-j4snf5w5xexk', 'balance': {'credits': '500', 'spent_credits': '0'}, 'user_default_credits': None, 'notification_intervals': {'balance_projection_seconds': [604800, 259200, 86400], 'balance_amount': [0], 'balance_depletion_seconds': [86400, 604800]}}]
INFO     [🔧TEST CONFIG]:conftest.py:291 Cleaning up 1 organisations
INFO     [🌐API_helper]:api_helper.py:54 GET https://api.dev.apolo.us/apis/admin/v1/clusters/default/orgs/regression-org-j4snf5w5xexk/projects
INFO     [🌐API_helper]:api_helper.py:182 Status: 200. Response: [{'name': 'regression-proj-iyep8dqjfj', 'cluster_name': 'default', 'org_name': 'regression-org-j4snf5w5xexk', 'is_default': False, 'default_role': 'reader', 'has_virtual_kube': False}]
INFO     [🔧TEST CONFIG]:conftest.py:308 Cleaning up 1 projects
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 200] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"items":[],"total":0,"page":1,"size":100,"pages":0}
INFO     [🌐API_helper]:api_helper.py:196 Delete project response: <ClientResponse(https://api.dev.apolo.us/apis/admin/v1/clusters/default/orgs/regression-org-j4snf5w5xexk/projects/regression-proj-iyep8dqjfj) [204 No Content]>
<CIMultiDictProxy('Access-Control-Allow-Credentials': 'true', 'Date': 'Wed, 08 Oct 2025 02:01:20 GMT', 'Server': 'Python/3.13 aiohttp/3.12.15', 'Vary': 'Origin', 'x-service-version': 'platform-admin/0.0.0.post1.dev0+4cdab15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')>

INFO     [🌐API_helper]:api_helper.py:189 Delete organization response: <ClientResponse(https://api.dev.apolo.us/apis/admin/v1/orgs/regression-org-j4snf5w5xexk) [200 OK]>
<CIMultiDictProxy('Access-Control-Allow-Credentials': 'true', 'Content-Length': '274', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Wed, 08 Oct 2025 02:01:21 GMT', 'Server': 'Python/3.13 aiohttp/3.12.15', 'Vary': 'Origin', 'x-service-version': 'platform-admin/0.0.0.post1.dev0+4cdab15', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000')>

INFO     [🔧TEST CONFIG]:conftest.py:326 Removed organisation: regression-org-j4snf5w5xexk
INFO     [🔧TEST CONFIG]:conftest.py:331 Closing all browser sessions
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:430 [HTTP 401] GET https://api.dev.apolo.us/apis/apps/v2/instances?org=regression-org-j4snf5w5xexk&project=regression-proj-iyep8dqjfj&cluster=default&size=100
Request Body:
<not available>
Response Body (first 1000 chars):
{"detail":{"missing":[{"uri":"app://default/regression-org-j4snf5w5xexk/regression-proj-iyep8dqjfj","action":"read"}]}}
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
WARNING  [🔧TEST CONFIG]:conftest.py:354 Failed to close browser: 
WARNING  [🔧TEST CONFIG]:conftest.py:339 Failed to stop Playwright: Event loop is closed
WARNING  [🔧TEST CONFIG]:conftest.py:347 Failed to close context: 
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR    asyncio:base_events.py:1879 Exception in callback ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228
handle: <Handle ProtocolCallback.__init__.<locals>.cb() at /home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py:228>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/apolo-test-automation/apolo-test-automation/.venv/lib/python3.13/site-packages/playwright/_impl/_connection.py", line 232, in cb
    self.future.cancel()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/opt/hostedtoolcache/Python/3.13.7/x64/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed