Your root certificates are out of date.
You are using certifi 2025.7.14, however 2025.8.3 is available.
Please consider upgrading certifi package, e.g.:
    python -m pip install --upgrade certifi
or
    conda update certifi

ERROR: Not enough permissions ({"missing": [{"uri": "cluster://default/users/regression-5fuceonhct", "action": "read"}]})